#!/usr/bin/env python
from generate_dbt_data_dictionary import DbtDataDictionary

print("Executing Pre-Commit Hook")

MODELS_DIR = 'dags\dbt\models'
SCHEMA_FILE_PATH = MODELS_DIR + '\\auto_schema.yml'
SEED_FILE_PATH = 'dags\dbt\seeds\data_dictionary.csv'

dd = DbtDataDictionary(MODELS_DIR)
dd.generate_dbt_schema(SCHEMA_FILE_PATH)
dd.generate_dbt_seed(SEED_FILE_PATH)
