FROM quay.io/astronomer/ap-airflow:2.2.4-onbuild
ENV AIRFLOW_VAR_SNOWFLAKE_ACCOUNT=XTA75274
ENV AIRFLOW_VAR_SNOWFLAKE_USERNAME=airflow
ENV AIRFLOW_VAR_SNOWFLAKE_PASSWORD=Airflow12
ENV AIRFLOW_VAR_SNOWFLAKE_TRANSFORM_WAREHOUSE_NAME=TRANSFORM
# Add additional variables as needed