
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt'
version: '1.0.0'
config-version: 2


profile: 'dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-paths: ../../dbt_logs

target-path: '../../dbt_target'
clean-targets:
  - '../../dbt_target'
on_run_start: # the `on_run_start` hook allows you to specify what executes first on dbt run
  - '{{ create_item_parse() }}'

models:
  dbt:
    +snowflake_warehouse: warehouse_name # name of warehouse to use
    enabled: true
    datalake: # or other name for extract schema name
      +materialized: incremental
      +database: db_name # name of db to use
    dw: # or other name for load schema name
      +materialized: table
