
name: 'demo'
version: '1.0.0'
config-version: 2


profile: 'demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: ../../dbt_logs
target-path: "../../dbt_target"  
clean-targets:         
  - "../../target"
#on_run_start: # the `on_run_start` hook allows you to specify what executes first on dbt run
#  - '{{ create_item_parse() }}'

models:
  demo:
    +snowflake_warehouse: AIRBYTE_WAREHOUSE # name of warehouse to use
    enabled: true
    dw: # or other name for load schema name
      +materialized: table
