demo:
  target: dev
  outputs:
    dev:
      account: pn17132.us-east-2.aws
      database: AIRBYTE
      password: Bacolod@16
      role: ACCOUNTADMIN
      schema: DW
      threads: 8
      type: snowflake
      user: CHRIS
      warehouse: COMPUTE_WH