demo:
  target: dev
  outputs:
    dev:
      account: <account_name>
      database: <db>
      password: <password>
      role: <account_role>
      schema: <schema>
      threads: 8
      type: snowflake
      user: <user>
      warehouse: <warehouse>