dbt:
  target: dev
  outputs:
    dev:
      account: "{{ env_var('AIRFLOW_VAR_SNOWFLAKE_ACCOUNT') }}"
      database: SHARETOWN
      password: "{{ env_var('AIRFLOW_VAR_SNOWFLAKE_PASSWORD') }}"
      role: SYSADMIN
      schema: DW
      threads: 8
      type: snowflake
      user: "{{ env_var('AIRFLOW_VAR_SNOWFLAKE_USERNAME') }}"
      warehouse: "{{ env_var('AIRFLOW_VAR_SNOWFLAKE_TRANSFORM_WAREHOUSE_NAME') }}"